# CP ASSIGNMENT-2

# REG NO: 21UAI102


# INHERITANCE
## SINGLE INHERTANCE

In [46]:
# single inheritance using protected access modifier
class emp:
    def __init__(self,name,income):
        #protected data members initialization
        self._name=name
        self._income=income
class hr(emp):
    def display(self):
        print("NAME:",self._name)
        print("INCOME",self._income)
    def dec(self):
        print('FULL STACK DEVELOPER')
hrobj=hr('velan',4532222)
hrobj.display()
hrobj.dec()

NAME: velan
INCOME 4532222
FULL STACK DEVELOPER


## MULTILEVEL INHERITANCE

In [52]:
class gfather:
    gfname='A'
    gfage=30
class father(gfather):
    fname='B'
    fage=5
class son(father):
    sname='C'
    sage=1
sobj=son()
print(sobj.gfname,'\n',sobj.gfage)


A 
 30


## MULTIPLE INHERITANCE

In [53]:
class father:
    fname='A'
    fage=34
class mother:
    mname='B'
    mage=16
class son(father,mother):
    sname='C'
    sage=5
sobj=son()
print("FATHER DETAILS:")
print(sobj.fname,"\n",sobj.fage)
print("\n")
print("MOTHER DETAILS:")
print(sobj.mname,"\n",sobj.mage)

FATHER DETAILS:
A 
 34


MOTHER DETAILS:
B 
 16


## HIERARCHIAL INHERITANCE

In [55]:
class university:
    uid=100
    uname="ABC UNIVERSITY"
class arts(university):
    aid=123
    aname="ABC ARTS & SCIENCE"
class engg(university):
    eid=245
    ename="ABC ENGINEERING COLLEGE"
class medical(university):
    mid=331
    mname="ABC MEDICAL COLLEGE & HOSPITAL"
class arch(university):
    arid=445
    arname="ABC SCHOOL OF ARCHITECTURE"
eobj=engg()
print(eobj.eid,"\n",eobj.ename)

245 
 ABC ENGINEERING COLLEGE


## HYBRID INHERITANCE

In [56]:
class GrandPa:
    def __init__(self):
        print("Grand father")

class Father(GrandPa):
    def __init__(self):
        super().__init__()
        print("Father")

class Mother(GrandPa):
    def __init__(self):
        super().__init__()
        print("Mother")


class child(Father, Mother):
    def __init__(self):
        super().__init__()
        print("Child")

c = child()


Grand father
Mother
Father
Child


## ACCESS MODIFIERS

In [57]:
#private inheritance
class emp:
    def __init__(self,eid,name):
        self._eid=eid
        self._name=name
e1=emp(3,'HI')
e1._eid

3

In [58]:
#private data members initialization
class emp:
    def __init__(self,emid,name):
        self.__eid=emid 
        self.__ename=name
e1=emp(1,"k")

# protected data members initialization
class job:
    def __init__(self,name,role):
        self._name=name 
        self._role=role
    def displaydata(self):
        print("name:",self._name)
        print("role:",self._role)
class hr(job):
    print("COLLEGE")
o1=hr('VELAN','STUDENT') 
o1.displaydata()



COLLEGE
name: VELAN
role: STUDENT


In [59]:
#public data members initialization
class emp:
    def __init__(self,name,height,weight):
        self.sname=name # all data members are public by default 
        self.sheight=height # . is used to initialize public data members
        self.sweight=weight
    def display(self):
        print("NAME:",self.sname)
        print("HEIGHT:",self.sheight)
        print("WEIGHT:",self.sweight)
o1=emp('VELAN',180,85)
o1.display()

NAME: VELAN
HEIGHT: 180
WEIGHT: 85


## NUMPY AGGREGATORS

In [60]:
import numpy as np
x=np.array([[1,3,5,2],[5,3,5,5],[9,1,1,2]])
print(np.max(x),np.min(x),np.sum(x))

9 1 42


In [61]:
m=np.random.randint(1,50,(3,4))
print(m)
print(m.sum())
print("sum row-wise:",np.sum(x,axis=1))
print("sum col-wise:",np.sum(x,axis=0))
print("max element of each col:",np.max(x,axis=0))
print("min element of each col:",np.min(x,axis=0))


[[ 7 48 24  2]
 [43 36 44 49]
 [26  4 36 25]]
344
sum row-wise: [11 18 13]
sum col-wise: [15  7 11  9]
max element of each col: [9 3 5 5]
min element of each col: [1 1 1 2]


In [62]:
import numpy as np
print(np.product([[1,6],[2,4]]))
print(np.mean([[2,6],[6,8]]))
print(np.std([[2,4],[6,4]]))
print(np.var([[2,2],[6,8]]))
x=np.array([[2,4],[6,2]])
print(np.argmax([1,2,3,4]))
print(np.argmin([1,2,3,4]))
b=np.array([True,True,True,False])
print(np.all(b))
print(np.any(b))
print(np.median([1,2,3,4,5]))

48
5.5
1.4142135623730951
6.75
3
0
False
True
3.0


## COMPARISION,MASKS AND BOOLEAN ARRAYS IN NUMPY

In [63]:
#boolean operations
import numpy as np
x=np.array([1,2,5,3,2])
print(x<2)
print(x>2)
print(x<=2)
print(x>=2)
print(x!=2)
print(x==2)

[ True False False False False]
[False False  True  True False]
[ True  True False False  True]
[False  True  True  True  True]
[ True False  True  True False]
[False  True False False  True]


In [64]:
4*x==(x**4)

array([False, False, False, False, False])

In [65]:
bool(22 and 0)

False

In [66]:
x=np.array([1,3,1,0,1,1],dtype=bool)
y=np.array([1,1,1,0,1,0],dtype=bool)

In [67]:
x&y

array([ True,  True,  True, False,  True, False])

In [68]:
x|y

array([ True,  True,  True, False,  True,  True])

In [69]:
x!=y

array([False, False, False, False, False,  True])

In [70]:
x^y

array([False, False, False, False, False,  True])

In [71]:
np.all(x) 

False

In [72]:
np.any(y)

True

## EXCEPTION HANDLING

In [73]:
#zero division error
def fun(a,b):
    try:
        c=a+b/(a-b)
    except ZeroDivisionError:
        print("Error due to divided by 0")
        
    else:
        print(c)
    finally:
        print("error handling learnt succesfully")
fun(2,2)      

    

Error due to divided by 0
error handling learnt succesfully


In [74]:
cgpa=9
try:
    if(cgpa>9):
        print("distinction")
except SyntaxError:
    print("syntax error")



In [75]:
list1 = ['x',3, 2, 3,-9.6]
try: 
    print ("Second element =",list1[1])
    print ("Sixth element =",list1[5]) #trying to access out of range element
  
except:
    print ("An error occurred")

Second element = 3
An error occurred


In [76]:
def func1(a , b):
    try:
        c = ((a+b) / (a-b))
    except ZeroDivisionError:
        print ("dividing a/b is 0")
    else:
        print (c)  
        
func1(1,1)
func1(3,4)

dividing a/b is 0
-7.0


In [77]:
try:
    raise NameError("dgs") # Raise Error
except NameError:
    print ("An exception")
    

An exception
